apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marvel-canary-path-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: marvel.assy.com
      http:
        paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: deploy1-service
               port:
                 number: 80
          # Route all traffic that starts with /v1 to deploy1-service
          - path: /v1
            pathType: Prefix   # Match all subpaths under /v1
            backend:
              service:
                name: deploy1-service
                port:
                  number: 80
          # Route all traffic that starts with /v2 to deploy2-service
          - path: /v2
            pathType: Prefix   # Match all subpaths under /v2
            backend:
              service:
                name: deploy2-service
                port:
                  number: 80
