apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marvel
      version: v2
  #strategy:
    #type: RollingUpdate
   # rollingUpdate:
    #  maxSurge: 1
    #  maxUnavailable: 1
  template:
    metadata:
      labels:
        app: marvel
        version: v2
    spec:
      containers:
        - name: marvel-container2
          image: 688567283917.dkr.ecr.us-east-1.amazonaws.com/marvel:v2
          ports:
            - containerPort: 8081
          #readinessProbe:
          #  httpGet:
           #   path: /health
            #  port: 8081
            #initialDelaySeconds: 20
            #periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-service
spec:
  selector:
    app: marvel
    version: v2
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30080
  type: NodePort
